//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VKHGDDTNN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Picture_GroupPicture
    {
        public string groupName { get; set; }
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public string Link { get; set; }
        public int Position { get; set; }
        public int Ord { get; set; }
        public bool Active { get; set; }
        public Nullable<int> Width { get; set; }
        public Nullable<int> Height { get; set; }
        public Nullable<int> Click { get; set; }
        public string Target { get; set; }
        public Nullable<int> IdGroup { get; set; }
    }
}
